fixes #322 check for null
fixes #322 

ig the main issue was an api issue checking for null should work fine
otherwise we can add semver validation via regex

diff --git a/.github/workflows/lychee-version.yml b/.github/workflows/lychee-version.yml
--- a/.github/workflows/lychee-version.yml
+++ b/.github/workflows/lychee-version.yml
@@ -25,7 +25,13 @@ jobs:
         run: |
           echo "Fetching the latest lychee release version..."
           release=$(curl -s https://api.github.com/repos/lycheeverse/lychee/releases/latest | jq -r .tag_name)
-          release=${release#lychee-} # Strip the 'lychee-' prefix
+          release=${release#lychee-}
+
+          if [ -z "$release" ] || [ "$release" == "null" ]; then
+            echo "Error: Could not fetch release version"
+            exit 1
+          fi
+          
           echo "Latest release version fetched: $release"
           echo "release_version=$release" >> $GITHUB_OUTPUT
 
