Add `failIfEmpty` argument (fixes #84) (#86)
* Add fail if empty argument

If no links were found during a run, this could indicate a configuration
issue. In order to warn users, this new option allows failing the pipeline
in such a scenario.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,18 +1,19 @@
 on:
-  - repository_dispatch
-  - workflow_dispatch
-  - push
-  - pull_request
+  push:
+    branches:
+      - master
+  pull_request:
+  workflow_dispatch:
+  repository_dispatch:
 
 env:
   CUSTOM_OUTPUT_RELATIVE_PATH: lychee/custom_output.md
   CUSTOM_OUTPUT_ABSOLUTE_PATH: /tmp/report.md
   CUSTOM_OUTPUT_DUMP_PATH: /tmp/dump.md
-    
+
 jobs:
   lychee-action:
     runs-on: ubuntu-latest
-    continue-on-error: true
     name: Test the lychee link checker action
     steps:
       - name: Checkout
@@ -57,7 +58,7 @@ jobs:
         with:
           output: "${{ env.CUSTOM_OUTPUT_RELATIVE_PATH }}"
           debug: true
-          
+
       - name: test custom output relative path - validation
         run: |
           echo "Checking custom output file at ${{ env.CUSTOM_OUTPUT_RELATIVE_PATH }}"
@@ -68,13 +69,13 @@ jobs:
             echo "Found. Contents:"
             cat "${{ env.CUSTOM_OUTPUT_RELATIVE_PATH }}"
           fi
-         
+
       - name: test custom output absolute path - creation
         uses: ./
         with:
           output: "${{ env.CUSTOM_OUTPUT_ABSOLUTE_PATH }}"
           debug: true
-          
+
       - name: test custom output absolute path - validation
         run: |
           echo "Checking custom output file at ${{ env.CUSTOM_OUTPUT_ABSOLUTE_PATH }}"
@@ -92,7 +93,7 @@ jobs:
           args: --dump './**/*.md' './**/*.html' './**/*.rst'
           output: "${{ env.CUSTOM_OUTPUT_DUMP_PATH }}"
           debug: true
-          
+
       - name: test dump with custom output path - validation
         run: |
           echo "Checking dump output file at ${{ env.CUSTOM_OUTPUT_DUMP_PATH }}"
@@ -103,6 +104,28 @@ jobs:
             echo "Found. Contents:"
             cat "${{ env.CUSTOM_OUTPUT_DUMP_PATH }}"
           fi
+
+      - name: test failIfEmpty - no links in input should fail the pipeline
+        id: fail_if_empty_test
+        uses: ./
+        with:
+          args: --verbose --no-progress fixtures/empty.md
+          debug: true
+        continue-on-error: true
+
+      # Explictly check the exit code of the previous step
+      # as it's expected to fail
+      - name: Check failIfEmpty
+        if: steps.fail_if_empty_test.outcome != 'failure'
+        run: |
+          echo "FailIfEmpty should have failed because no links were found."
+          exit 1
+
+      - name: test disable failIfEmpty - it's okay if no links are found
+        uses: ./
+        with:
+          args: --no-progress fixtures/empty.md
+          failIfEmpty: false
 
       - name: Install jq
         run: sudo apt-get install jq
