Fix bugs about the exit code (#262)
-   **fix: Make `fail: false` effective even when `failIfEmpty: true`**

This commit also makes sure `outputs.exit_code` is “The exit code returned from Lychee”. `failIfEmpty` no longer changes it to `1`.

Relevant docs:
- [Setting exit codes for actions - GitHub Docs](https://docs.github.com/en/actions/sharing-automations/creating-actions/setting-exit-codes-for-actions)
- [exit - POSIX Programmer's Manual](https://manned.org/exit.1posix)

Relates to #86, #128, #145, #245, and #251.

-   **fix: Update `env.exit_code` to `outputs.exit_code`**

The previous expression always gives `false`.
Both `env.exit_code` and `env.lychee_exit_code` are `null`, probably since the docker→composite refactor #128. When GitHub evaluates the expression, it finds the types do not match, and coerces them to number, namely, `null` → `0`.

See [Evaluate expressions in workflows and actions - GitHub Docs](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#operators).

Relates to #253.



Co-authored-by: Sebastiaan Speck <12570668+sebastiaanspeck@users.noreply.github.com>

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -125,6 +125,28 @@ jobs:
           echo "Output set in args and action input should have failed."
           exit 1
 
+      - name: test fail - a lychee error should fail the pipeline
+        id: fail_test
+        uses: ./
+        with:
+          args: --verbose --no-progress foo.bar
+          debug: true
+        continue-on-error: true
+
+      # Explicitly check the exit code of the previous step
+      # as it's expected to fail
+      - name: Check fail
+        if: steps.fail_test.outcome != 'failure'
+        run: |
+          echo "Fail should have failed because the URL is invalid."
+          exit 1
+
+      - name: test disable fail - it's okay if lychee throws an error
+        uses: ./
+        with:
+          args: --no-progress foo.bar
+          fail: false
+
       - name: test failIfEmpty - no links in input should fail the pipeline
         id: fail_if_empty_test
         uses: ./
@@ -146,6 +168,40 @@ jobs:
         with:
           args: --no-progress fixtures/empty.md
           failIfEmpty: false
+
+      - name: test disable failIfEmpty - a lychee error should still fail the pipeline
+        id: fail_but_not_failIfEmpty_test
+        uses: ./
+        with:
+          args: --verbose --no-progress foo.bar
+          failIfEmpty: false
+          debug: true
+        continue-on-error: true
+
+      # Explicitly check the exit code of the previous step
+      # as it's expected to fail
+      - name: Check fail when failIfEmpty is disabled
+        if: steps.fail_but_not_failIfEmpty_test.outcome != 'failure'
+        run: |
+          echo "Fail should have failed because the URL is invalid, even though failIfEmpty is disabled."
+          exit 1
+
+      - name: test disable fail - no links in input should still fail the pipeline
+        id: failIfEmpty_but_not_fail_test
+        uses: ./
+        with:
+          args: --verbose --no-progress fixtures/empty.md
+          fail: false
+          debug: true
+        continue-on-error: true
+
+      # Explicitly check the exit code of the previous step
+      # as it's expected to fail
+      - name: Check failIfEmpty when fail is disabled
+        if: steps.failIfEmpty_but_not_fail_test.outcome != 'failure'
+        run: |
+          echo "FailIfEmpty should have failed because no links were found, even though fail is disabled."
+          exit 1
 
       - name: Install jq
         run: sudo apt-get install jq
