Set exit_code correctly as output (#245)

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -194,3 +194,21 @@ jobs:
         uses: ./
         with:
           token: ${{ secrets.CUSTOM_TOKEN }}
+
+      - name: Test exit code set in steps-output
+        id: lychee_exit_code_test
+        uses: ./
+        with:
+          args: -- inputdoesnotexist
+        continue-on-error: true
+
+      - name: Check exit code in steps.outputs
+        run: |
+          echo "Lychee exit code: ${{ steps.lychee_exit_code_test.outputs.exit_code }}"
+          if [[ "${{ steps.lychee_exit_code_test.outputs.exit_code }}" == "1" ]]; then
+            echo "Lychee correctly failed with exit code 1"
+          else
+            echo "Unexpected exit code: ${{ steps.lychee_exit_code_test.outputs.exit_code }}"
+            echo "Expected exit code 1"
+            exit 1
+          fi
